# Python and regression matrix algebra

Load libraries:

In [29]:
import numpy as np # basic linear algebra 
import scipy.stats # for generation of random variables

In what follows, set $n$ to 100 and $k$ to 3. Report results with precision of 3 digitals.

In [30]:
n = 100 # number of observations
k = 3 # number of independent variables
np.set_printoptions(precision=3) # number of signs after comma in the whole notebook

1. Generate an $n \times k$ matrix of independent standard normal random variables using a random number generator, call it $X$. Compute and report $X' X$.

In [3]:
X = scipy.stats.norm.rvs(loc=0, scale=1, size=(n, k))
# norm - noraml, rvs - random variable sampling
# loc - mean, scale - standard deviation
# note that we created a sample of a random vector with 
# three independent random variables in it! 
X

array([[-3.987e-01,  5.179e-01, -1.951e+00],
       [ 1.655e-01, -1.048e+00, -1.927e+00],
       [ 6.705e-01,  4.408e-01, -1.727e-02],
       [ 3.498e-01,  9.733e-01,  1.462e+00],
       [ 1.180e+00,  6.634e-01,  1.683e+00],
       [ 1.706e-02, -1.784e+00,  9.140e-01],
       [ 9.932e-01,  1.901e+00,  6.875e-01],
       [ 1.214e+00,  1.799e+00, -3.990e-01],
       [-4.201e-02, -5.363e-01, -2.226e+00],
       [ 3.868e-01,  5.269e-01, -1.798e-01],
       [ 7.628e-01, -7.370e-01, -1.217e+00],
       [-1.349e+00,  4.310e-01, -1.755e-01],
       [ 2.228e+00,  2.929e-03,  8.816e-01],
       [-1.961e-01, -8.065e-01, -1.913e+00],
       [-2.160e-01,  9.476e-01, -1.168e+00],
       [-2.466e-01, -3.510e-01, -1.442e-01],
       [ 1.051e-01, -1.662e-01, -5.783e-01],
       [-1.398e+00,  1.528e-01,  4.400e-01],
       [ 4.518e-01, -1.223e+00, -3.485e-01],
       [ 1.895e-02,  1.324e+00, -2.345e+00],
       [ 3.275e-01,  4.421e-01, -6.775e-01],
       [-1.510e-01, -7.346e-01, -1.250e+00],
       [-7

In [4]:
X.T.shape # tranformed matrix

(3, 100)

In [5]:
X.T @ X # matrix multiplication

array([[ 91.748,  15.547,  13.622],
       [ 15.547,  89.698,  -9.799],
       [ 13.622,  -9.799, 116.162]])

2. Using cycling in $i$, compute $\sum_{i=1}^n x_i x_i'$, where each $k \times 1$ vector $x_i$ is the transposed $i$th row of $X$. Report this sum and make sure it coincides with $X' X$.

In [6]:
i = 1 # take the second row
X[i][:, np.newaxis] # get a column vector from it - now it's interpreted
# by python as 2D objest, instead of 1D object

array([[ 0.165],
       [-1.048],
       [-1.927]])

In [7]:
X[i][np.newaxis, :] # row vector

array([[ 0.165, -1.048, -1.927]])

In [8]:
X[i][:, np.newaxis] @ X[i][np.newaxis, :] # column vector * row vector

array([[ 0.027, -0.173, -0.319],
       [-0.173,  1.098,  2.019],
       [-0.319,  2.019,  3.712]])

In [9]:
# bsic cycle
for i in range(5):
    print(i)

0
1
2
3
4


In [10]:
# compute the sum of X'X for each observation (#n)
S = 0
for i in range(n):
    S += X[i][:, np.newaxis] @ X[i][np.newaxis, :]
S

array([[ 91.748,  15.547,  13.622],
       [ 15.547,  89.698,  -9.799],
       [ 13.622,  -9.799, 116.162]])

Coinsides with the precious result.

In [11]:
S == X.T @ X # although python is having troubles with stroring float values

array([[False,  True, False],
       [ True,  True,  True],
       [False,  True, False]])

In [12]:
np.allclose(S, X.T @ X) # apply the method for close proximity

True

In [13]:
?np.allclose # anout the method

Signature:       np.allclose(a, b, rtol=1e-05, atol=1e-08, equal_nan=False)
Call signature:  np.allclose(*args, **kwargs)
Type:            _ArrayFunctionDispatcher
String form:     <function allclose at 0x00000160B359E840>
File:            c:\users\popov\anaconda3\envs\nes\lib\site-packages\numpy\core\numeric.py
Docstring:      
Returns True if two arrays are element-wise equal within a tolerance.

The tolerance values are positive, typically very small numbers.  The
relative difference (`rtol` * abs(`b`)) and the absolute difference
`atol` are added together to compare against the absolute difference
between `a` and `b`.

NaNs are treated as equal if they are in the same place and if
``equal_nan=True``.  Infs are treated as equal if they are in the same
place and of the same sign in both arrays.

Parameters
----------
a, b : array_like
    Input arrays to compare.
rtol : float
    The relative tolerance parameter (see Notes).
atol : float
    The absolute tolerance parameter (see Note

3. Compute and report a sample mean and sample variance of the random vector $x$ whose sample is represented by $X$: How close are they to the population mean and population variance of $x$?

In [14]:
np.mean(X, axis=0) # compute sample mean of a random variable vector x, which sample 
# is represented by the matrix X. 

array([-0.124, -0.007, -0.1  ])

In [15]:
?np.cov # note that for 3 random variables, we have not a covariance matrix,
# but a covariance cube))

Signature:      
np.cov(
    m,
    y=None,
    rowvar=True,
    bias=False,
    ddof=None,
    fweights=None,
    aweights=None,
    *,
    dtype=None,
)
Call signature:  np.cov(*args, **kwargs)
Type:            _ArrayFunctionDispatcher
String form:     <function cov at 0x00000160B36CCFE0>
File:            c:\users\popov\anaconda3\envs\nes\lib\site-packages\numpy\lib\function_base.py
Docstring:      
Estimate a covariance matrix, given data and weights.

Covariance indicates the level to which two variables vary together.
If we examine N-dimensional samples, :math:`X = [x_1, x_2, ... x_N]^T`,
then the covariance matrix element :math:`C_{ij}` is the covariance of
:math:`x_i` and :math:`x_j`. The element :math:`C_{ii}` is the variance
of :math:`x_i`.

See the notes for an outline of the algorithm.

Parameters
----------
m : array_like
    A 1-D or 2-D array containing multiple variables and observations.
    Each row of `m` represents a variable, and each column a single
    observation

In [32]:
np.cov(X.T) # compute our sample 3D covariance matrix 
# X.T - specifics of the method 

array([[ 0.911,  0.156,  0.125],
       [ 0.156,  0.906, -0.1  ],
       [ 0.125, -0.1  ,  1.163]])

Note that a theoretical covariance matrix is just aт identity matrix (1 on the diagonal - std = 1, 0 in other positions - our random variables are independent). However, our sample covariance matrix has only 100 observations, thus, it's only approximately like that. 

In [17]:
np.zeros(3) # get the theoretical mean 

array([0., 0., 0.])

In [33]:
np.identity(3) # get the theoretical covariance matrix 

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

4. What is the rank of $n^{-1} X' X$? What is the rank of $Q_{xx} \equiv \mathbb{E}[xx']$? What is the rank of $x_i x_i'$? Compute and report the inverse of $n^{-1} X' X$. What is the inverse of $Q_{xx}$?

In [19]:
np.linalg.matrix_rank(X.T @ X / n)

3

It indeed shoyld have full rank - becuase our random variables are independent (no multicollinearity).

In [34]:
Qxx = np.identity(3) # this is the th. covariance matrix.
np.linalg.matrix_rank(Qxx)

3

This is a theoretical analogue of the previous sample matrix.

In [35]:
i = 5 # for the particular row - realization of the random vector
np.linalg.matrix_rank(X[i][:, np.newaxis] @ X[i][np.newaxis, :])

1

It is only one, as it's a multiplication of the two vectors, each with the rank of 1 (linear algebra).

In [36]:
np.linalg.inv(X.T @ X / n) # computing the inverse matrix

array([[ 1.149, -0.216, -0.153],
       [-0.216,  1.166,  0.124],
       [-0.153,  0.124,  0.889]])

Its th. analogue.

In [23]:
np.linalg.inv(Qxx)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

5. Verify in a similar vein that
$$ \sum_{i=1}^{n} \omega_i x_i x_i' = X' \Omega X $$
and
$$ \sum_{i=1}^{n} \frac{x_i x_i'}{\omega_i} = X' \Omega^{-1} X, $$
where $\Omega = \text{diag}\{\omega_i\}_{i=1}^{n}$ is an arbitrary diagonal $n \times n$ matrix containing (heterogeneous and non-zero!) $\omega_i$ on the main diagonal.

In [24]:
# get the log-normal distribution vector 
weights = np.exp(scipy.stats.norm.rvs(loc=0, scale=1, size=n))
# now construct the diagonal matrix from our vector
Omega = np.diag(weights)
Omega

array([[0.725, 0.   , 0.   , ..., 0.   , 0.   , 0.   ],
       [0.   , 0.797, 0.   , ..., 0.   , 0.   , 0.   ],
       [0.   , 0.   , 0.617, ..., 0.   , 0.   , 0.   ],
       ...,
       [0.   , 0.   , 0.   , ..., 2.856, 0.   , 0.   ],
       [0.   , 0.   , 0.   , ..., 0.   , 0.315, 0.   ],
       [0.   , 0.   , 0.   , ..., 0.   , 0.   , 5.1  ]])

In [25]:
# calculate the first LHS 
S = 0
for i in range(n):
    S += X[i][:, np.newaxis] @ X[i][np.newaxis, :] * weights[i]
S

array([[153.437,  33.099,   6.534],
       [ 33.099, 168.706, -17.647],
       [  6.534, -17.647, 196.721]])

In [26]:
# calculate the first RHS 
X.T @ Omega @ X

array([[153.437,  33.099,   6.534],
       [ 33.099, 168.706, -17.647],
       [  6.534, -17.647, 196.721]])

In [27]:
# calculate the second LHS
S = 0
for i in range(n):
    S += X[i][:, np.newaxis] @ X[i][np.newaxis, :] / weights[i]
S

array([[134.756,  40.982,  23.904],
       [ 40.982, 181.869,   9.425],
       [ 23.904,   9.425, 196.447]])

In [28]:
# calculate the second RHS
X.T @ np.linalg.inv(Omega) @ X

array([[134.756,  40.982,  23.904],
       [ 40.982, 181.869,   9.425],
       [ 23.904,   9.425, 196.447]])